Antlr version 3 must be 3.0.1 instead of the currently latest 3.2, because otherwise oAW has a problem (in module codegen, java.lang.NoSuchMethodError: org.antlr.runtime.Parser.match(Lorg/antlr/runtime/IntStream;ILorg/antlr/runtime/BitSet;)V)
git-svn-id: https://alma-svn.aoc.nrao.edu/p2/trunk/ACS@141973 523d945c-050c-4681-91ec-863ad3bb968a