Split the way inspect.stack() is used to see if we can get better information a test failure that happens in __getCallerName(): "AttributeError: 'NoneType' object has no attribute '_getframe'"
git-svn-id: https://alma-svn.aoc.nrao.edu/p2/trunk/ACS@194726 523d945c-050c-4681-91ec-863ad3bb968a